# Generated by Django 2.2.2 on 2019-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190824_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitch_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
