# Generated by Django 2.2.2 on 2019-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190901_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='twitch_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
