# Generated by Django 2.2.2 on 2019-09-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190901_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
