# Generated by Django 2.2.2 on 2019-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='mode',
            field=models.CharField(choices=[('rr', 'Round Robin'), ('se', 'Single Elimination'), ('de', 'Double Elimination')], default='se', max_length=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(null=True),
        ),
    ]
