# Generated by Django 2.2.2 on 2019-08-03 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0002_auto_20190731_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.IntegerField(null=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Bracket')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player_one', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player_two', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player_three', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player_four', to=settings.AUTH_USER_MODEL)),
                ('player5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player_five', to=settings.AUTH_USER_MODEL)),
                ('player6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player_six', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_result', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('team2_result', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('depth_level', models.IntegerField(null=True)),
                ('bye_flag', models.BooleanField(null=True)),
                ('planned', models.BooleanField(null=True)),
                ('played', models.BooleanField(null=True)),
                ('winner', models.IntegerField(null=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Bracket')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
