# Generated by Django 2.2.2 on 2019-07-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
            preserve_default=False,
        ),
    ]
