# Generated by Django 2.2.2 on 2019-08-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_matchteam_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
