# Generated by Django 2.2.2 on 2019-07-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_registration_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
            preserve_default=False,
        ),
    ]
