# Generated by Django 2.2.2 on 2019-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190803_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
