# Generated by Django 2.2.2 on 2019-07-13 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0004_bracket_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player2_result',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_result',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
