# Generated by Django 2.2.2 on 2019-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20190803_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_creation_mode',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
