# Generated by Django 2.2.2 on 2019-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_registration_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bye_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='depth_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='planned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(null=True),
        ),
    ]
