# Generated by Django 2.2.2 on 2019-08-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190804_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Team'),
        ),
    ]
