# Generated by Django 2.2.2 on 2019-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20190724_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.IntegerField(null=True),
        ),
    ]
