# Generated by Django 2.2.2 on 2019-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20190804_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
