# Generated by Django 2.2.2 on 2019-07-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.Bracket'),
            preserve_default=False,
        ),
    ]
