# Generated by Django 2.2.2 on 2019-08-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_league_tournamentleagues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentLeagues',
            new_name='TournamentsInLeague',
        ),
    ]
