# Generated by Django 2.2.2 on 2019-08-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_auto_20190805_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsinleague',
            name='league',
        ),
        migrations.RemoveField(
            model_name='tournamentsinleague',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='TournamentsInLeague',
        ),
    ]
