# Generated by Django 2.2.2 on 2019-08-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_standings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='format',
            new_name='team_format',
        ),
    ]
