# Generated by Django 2.2.2 on 2019-08-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20190811_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.IntegerField(null=True),
        ),
    ]
