# Generated by Django 2.2.2 on 2019-08-11 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0016_tournament_format'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standings',
            new_name='Standing',
        ),
    ]
