# Generated by Django 2.2.2 on 2019-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_standing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
