# Generated by Django 2.2.2 on 2019-08-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_auto_20190811_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standing',
            old_name='time',
            new_name='result',
        ),
    ]
