# Generated by Django 2.2.2 on 2019-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_auto_20190811_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='result',
            field=models.DurationField(max_length=64, null=True),
        ),
    ]
