# Generated by Django 2.2.2 on 2019-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_remove_tournament_registration_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default='64', null=True),
        ),
    ]
