# Generated by Django 2.2.2 on 2019-08-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_auto_20190825_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tournament.Game'),
        ),
    ]
