# Generated by Django 2.2.2 on 2019-08-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_tournament_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='start_date',
            new_name='date',
        ),
    ]
