# Generated by Django 2.2.4 on 2019-08-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_auto_20190825_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game',
        ),
    ]
