# Generated by Django 2.2.2 on 2019-07-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
