# Generated by Django 2.2.2 on 2019-06-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
    ]
