# Generated by Django 2.2.2 on 2019-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
