# Generated by Django 2.2.2 on 2019-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190623_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='event',
            name='description_short',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='mode',
            field=models.CharField(choices=[('rr', 'Round Robin'), ('se', 'Single Elimination'), ('de', 'Double Elimination')], default='rr', max_length=2),
        ),
    ]
