# Generated by Django 2.2.2 on 2019-08-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_ratingpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='registration_end_date',
            new_name='end_date',
        ),
    ]
